# Generated by Django 4.0.3 on 2022-03-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('biography', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='CategoryBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categorybook',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('numberOfPage', models.IntegerField()),
                ('publicationDate', models.DateField()),
                ('author', models.ManyToManyField(to='bai5.author')),
                ('categoryBookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bai5.categorybook')),
                ('publisherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bai5.publisher')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
