# Generated by Django 4.0.3 on 2022-03-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bai5', '0002_alter_book_publicationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('techType', models.CharField(max_length=255)),
                ('typeCpu', models.CharField(max_length=255)),
                ('speed', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cpu',
            },
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('screen', models.CharField(max_length=255)),
                ('rearCamera', models.CharField(max_length=255)),
                ('frontCamera', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('ops', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
                ('warranty', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('displayType', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mobilephone',
            },
        ),
        migrations.CreateModel(
            name='VGA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('vram', models.CharField(max_length=255)),
                ('tech', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vga',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('screen', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('warranty', models.CharField(max_length=255)),
                ('ops', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bai5.cpu')),
                ('vga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bai5.vga')),
            ],
            options={
                'db_table': 'laptop',
            },
        ),
    ]
